name: cloudrun-deploy
on:
  push:
    branches:
      - main

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2


    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@v0
      with:
        service_account_email: ${{ secrets.GCP_EMAIL }}
        service_account_key: ${{ secrets.GCP_CREDENTIALS }}
        export_default_credentials: true
    
    # Configure Docker with Credentials
    - name: Configure Docker
      run: |
        gcloud auth configure-docker
      

    # Build the Docker image
    - name: Docker Login
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        ARTIFACT_REGISTRY:  ${{ secrets.ARTIFACT_REGISTRY}}
      run: | 
        echo '${{ secrets.GCP_CREDENTIALS }}' > key.json
        cat key.json | docker login -u _json_key --password-stdin ${{ secrets.ARTIFACT_REGISTRY }}
    - name: Build Image & Push
      env: 
        ARTIFACT_REGISTRY_REPO: ${{ secrets.ARTIFACT_REGISTRY_REPO }}
      run: | 
        docker build -t ${{ secrets.ARTIFACT_REGISTRY_REPO }}/app:latest .
        docker push ${{ secrets.ARTIFACT_REGISTRY_REPO }}/app:latest

    # Deploy image to Cloud Run
    - name: Deploy GCR
      run: |-
        gcloud run deploy hack-grupo-06-backend \
            --quiet \
            --region us-central1 \
            --image ${{ secrets.ARTIFACT_REGISTRY_REPO }}/app:latest \
            --platform “managed” \
            --allow-unauthenticated